//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Quiz_App.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Tbl_Questions
    {
        public int Q_ID { get; set; }
        public string Q_Text { get; set; }
        public string Op_A { get; set; }
        public string Op_B { get; set; }
        public string Op_C { get; set; }
        public string Op_D { get; set; }
        public string Correct_Op { get; set; }
        public Nullable<int> Q_FK_catid { get; set; }

        public virtual Tbl_Category Tbl_Category { get; set; }
    }

}
