//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Quiz_App.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Tbl_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Category()
        {
            this.Tbl_Questions = new HashSet<Tbl_Questions>();
        }

        public int Cat_ID { get; set; }
        public string Cat_Name { get; set; }
        public Nullable<int> Cat_FK_adid { get; set; }
        public string cat_encrypted { get; set; }

        public virtual Tbl_Admin Tbl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Questions> Tbl_Questions { get; set; }
    }
}
